### ISSUE TITLE
Kamailio Failed to start after fresh installation

### ISSUE THREAD

**Issue by cybertruss** [irontec/ivoz-api#1]
Kamailio failed to start after the installation of the Ivoz Provider standalone server. Installation is on a VPS with full root access and not behind NAT. I am using a single public IP for both proxyusers and proxytrunk. 

Below is output from journalctl -xe

Nov 21 02:59:32 W183 sync[26302]: Company and carrier balances updated successfully!
Nov 21 02:59:32 W183 systemd[1]: cgrates.service: Service hold-off time over, scheduling restart.
Nov 21 02:59:32 W183 systemd[1]: Stopped CGrateS Engine.
-- Subject: Unit cgrates.service has finished shutting down
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit cgrates.service has finished shutting down.
Nov 21 02:59:32 W183 systemd[1]: cgrates.service: Failed to reset devices.list: Operation not permitted
Nov 21 02:59:32 W183 systemd[1]: Started CGrateS Engine.
-- Subject: Unit cgrates.service has finished start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit cgrates.service has finished starting up.
--
-- The start-up result is done.
Nov 21 02:59:32 W183 systemd[1]: Started Ivozprovider Balances updater.
-- Subject: Unit ivozprovider-balances.service has finished start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit ivozprovider-balances.service has finished starting up.
--
-- The start-up result is done.
Nov 21 02:59:32 W183 cgr-engine[26304]: CGRateS <f8961a8> [26304]: Starting CGRateS CDRS service.
Nov 21 02:59:32 W183 cgr-engine[26304]: CGRateS <f8961a8> [26304]: Starting CGRateS SMKamailio service.
Nov 21 02:59:32 W183 cgr-engine[26304]: 2020/11/21 02:59:32 method Call has wrong number of ins: 4
Nov 21 02:59:32 W183 cgr-engine[26304]: CGRateS <f8961a8> [26304]: <CDRC> No enabled CDRC clients
Nov 21 02:59:32 W183 cgr-engine[26304]: CGRateS <f8961a8> [26304]: <HTTP> enabling handler for JSON-RPC
Nov 21 02:59:32 W183 cgr-engine[26304]: CGRateS <f8961a8> [26304]: <HTTP> enabling handler for WebSocket connections
Nov 21 02:59:32 W183 cgr-engine[26304]: 2020/11/21 02:59:32 method Call has wrong number of ins: 4
Nov 21 02:59:32 W183 cgr-engine[26304]: 2020/11/21 02:59:32 method ProcessExternalCdr has wrong number of ins: 2
Nov 21 02:59:32 W183 cgr-engine[26304]: 2020/11/21 02:59:32 method RateCDRs has wrong number of ins: 4
Nov 21 02:59:32 W183 cgr-engine[26304]: 2020/11/21 02:59:32 method RegisterHandlersToServer has wrong number of ins: 2
Nov 21 02:59:32 W183 cgr-engine[26304]: 2020/11/21 02:59:32 method Timezone has wrong number of ins: 1
Nov 21 02:59:32 W183 cgr-engine[26304]: KamEvapi:02:59:32  Attempting connect to Kamailio at: 127.0.0.1:8448
Nov 21 02:59:32 W183 cgr-engine[26304]: KamEvapi:02:59:32 <KamEvapi> Failed connecting to Kamailio at: 127.0.0.1:8448, error: dial tcp 127.0.0.1:8448: getsockopt: conne
Nov 21 02:59:32 W183 cgr-engine[26304]: CGRateS <f8961a8> [26304]: <HTTP> start listening at <trunks.ivozprovider.local:2080>
Nov 21 02:59:32 W183 cgr-engine[26304]: CGRateS <f8961a8> [26304]: Registering CDRS HTTP Handlers.
Nov 21 02:59:32 W183 unknown[26304]: CGRateS <f8961a8> [26304]: Registering CDRS RPC service.
Nov 21 02:59:32 W183 unknown[26304]: CGRateS <f8961a8> [26304]: <SMKamailio> error: dial tcp 127.0.0.1:8448: getsockopt: connection refused!
Nov 21 02:59:32 W183 unknown[26304]: CGRateS <f8961a8> [26304]: Stopped all components. CGRateS shutdown!

Output from kamtail-proxyusers

[Nov 21 02:31:48] rr [rr_mod.c:175]: mod_init(): outbound module not available
[Nov 21 02:31:48] permissions [permissions.c:598]: mod_init(): default allow file (/etc/kamailio/proxyusers/permissions.allow) not found => empty rule set
[Nov 21 02:31:48] permissions [permissions.c:612]: mod_init(): default deny file (/etc/kamailio/proxyusers/permissions.deny) not found => empty rule set
[Nov 21 02:31:48] dmq [dmq.c:228]: mod_init(): server_uri is not a socket the proxy is listening on
[Nov 21 02:31:48] <core> [core/sr_module.c:986]: init_mod(): Error while initializing module dmq (/usr/lib/x86_64-linux-gnu/kamailio/modules/dmq.so)
[Nov 21 02:31:48] <core> [core/sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized
Nov 21 02:31:48 systemd[1]: kamailio@users.service: Control process exited, code=exited status=255
Nov 21 02:31:48 systemd[1]: Failed to start Kamailio - the Open Source SIP Server.
Nov 21 02:31:48 systemd[1]: kamailio@users.service: Unit entered failed state.
Nov 21 02:31:48 systemd[1]: kamailio@users.service: Failed with result 'exit-code'.

output from kamtail-proxytrunks
-- Logs begin at Fri 2020-11-20 19:42:09 UTC. --
[Nov 21 02:31:48] rr [../outbound/api.h:52]: ob_load_api(): unable to import bind_ob - maybe module is not loaded
[Nov 21 02:31:48] rr [rr_mod.c:175]: mod_init(): outbound module not available
[Nov 21 02:31:48] rtpengine [rtpengine.c:1476]: mod_init(): Loading rtp proxy definitions from DB
[Nov 21 02:31:48] dmq [dmq.c:228]: mod_init(): server_uri is not a socket the proxy is listening on
[Nov 21 02:31:48] <core> [core/sr_module.c:986]: init_mod(): Error while initializing module dmq (/usr/lib/x86_64-linux-gnu/kamailio/modules/dmq.so)
[Nov 21 02:31:48] <core> [core/sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized
Nov 21 02:31:48 systemd[1]: kamailio@trunks.service: Control process exited, code=exited status=255
Nov 21 02:31:48 systemd[1]: Failed to start Kamailio - the Open Source SIP Server.
Nov 21 02:31:48 systemd[1]: kamailio@trunks.service: Unit entered failed state.
Nov 21 02:31:48 systemd[1]: kamailio@trunks.service: Failed with result 'exit-code'.

**Comment by Kaian** [comment]
Hi,

This is not the appropiate github project to report IvozProvider issues.


According to the logs it seems related to DMQ module but we haven't seen this problem before.
If you prefer, open an issue in main github project. Be sure to follow issue template and try to format logs between ``` code tags.
